### ISSUE TITLE
How does one view the data?

### ISSUE THREAD

**Issue by guyn2gis** [R-ArcGIS/r-sample-tools#1]
Is it possible to view a layer inside of R Studio?  arc.open just opens the metadata.  I want to plot inside of R Studio, how do I do that? or send to Pro what I do in  R Studio...  Is that possible?

**Comment by dpavlushko** [comment]
Use combination of arc.open + arc.select to pull data and geometry from your layer to a data.frame.

**Comment by guyn2gis** [comment]
I will take a look.  Thanks.  You can close the issue.

**Comment by scw** [comment]
Once you have a data frame from `arc.select`, you can use the standard plotting methods as @dpavlushko mentioned. You also can convert the data to an sp object with `arc.data2sp`. If you're plotting spatial data from R, this can be useful because the other packages for plotting can then take advantage of the spatial data for things like labeling the axes. Check out the [sp documentation](https://cran.r-project.org/web/packages/sp/vignettes/intro_sp.pdf) for examples.
